# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Run when master branch is updated'
  lane :master_updated do
    scheme = 'GitHubFeed'
    workspace = 'GitHubFeed.xcworkspace'
    project = 'GitHubFeed.xcodeproj'
    
    scan(
      scheme: scheme,
      code_coverage: true
    )

    slather(
      workspace: workspace,
      scheme: scheme,
      proj: project,
      use_bundle_exec: true,
      circleci: true,
      coveralls: true
    )
  end
end
