#!/usr/bin/ruby

file_content = <<EOM
/* 
  FILE AUTOGENERATED #{Time.now}
  DO NOT EDIT
*/

struct Secrets {
  struct GitHub {
    static let token = "#{ENV['GITHUB_ACCESS_TOKEN']}"
  }
}
EOM

File.open("#{ENV['SRCROOT']}/Sources/Support/Secrets.swift", "w") do |file|
  file.write(file_content)
end