#!/usr/bin/ruby

file_content = <<EOM
/* 
  FILE AUTOGENERATED #{Time.now}
  DO NOT EDIT
*/

struct Secrets {
  struct GitHub {
    static let token = "#{ENV['GITHUB_ACCESS_TOKEN']}"
  }
}
EOM

file_path = "#{ENV['SRCROOT']}/Sources/Support/Secrets.swift"

File.open(file_path, "w") do |file|
  file.write(file_content)
end
