#!/usr/bin/ruby

file_content = <<EOM
/* 
  FILE AUTOGENERATED #{Time.now}
  DO NOT EDIT
*/

struct Secrets {
  struct GitHub {
    static let token = "#{ENV['GITHUB_ACCESS_TOKEN']}"
  }
}
EOM

file = File.new("Sources/Support/Secrets.swift", "w")
file.puts(file_content)
file.close